### ISSUE TITLE
Using instance of Variable class in defining variables of Cpm

### ISSUE THREAD

**Issue by dynaryu** [jieunbyun/BNS-JT#16]
I guess Variable needs to be defined prior to Cpm.
In this case, there is no need to use v_info as they're already in the scope. 
Let me know your thoughts.

Caused a problem with sorting of new_child during product operation

**Comment by jieunbyun** [comment]
I agree. Thank you for the good idea : D

**Comment by dynaryu** [comment]
I created a branch and making some changes there. When I'm done, I'll merge it to the python branch. 
Also another important change that I'm considering is using 0-based index when writing C matrix. 
Let me know your thoughts.

**Comment by jieunbyun** [comment]
I agree on using 0-based indexing. In the context of Python, it makes more sense.
