### ISSUE TITLE
Replacing B of a Variable afterwards

### ISSUE THREAD

**Issue by jieunbyun** [jieunbyun/BNS-JT#34]
I am tryiing to build a function that automatically builds CPM from B&B result.
And regarding that, how can I update the "B" when a new composite state needs to be added? 

At the moment, if I type in (for some existing var1)
    var1.B = B_new
I get an error message reading
    AttributeError: can't set attribute

Could you help me with this..?
Thank you so much!

**Comment by dynaryu** [comment]
I've used namedtuple for Variable class, so it cannot be modified once it's created (i.e., immutable). If that's not the behavior you want, then let me know.

**Comment by jieunbyun** [comment]
Yes, I hope it can be changed so that they can be updated by B&B results (since B&B function requires variables to be defined beforehand).

**Comment by dynaryu** [comment]
It should work as intended. Otherwise let me know.

**Comment by jieunbyun** [comment]
Yes it works! Thank you : D
