### ISSUE TITLE
line 160 in the gen_bnb

### ISSUE THREAD

**Issue by dynaryu** [jieunbyun/BNS-JT#37]
Can you check line 160 in the gen_bnb.py?

sum([x in y for y in rules])

I can't figure out what x is. 
Is the last value from the previous loop?
Thanks.

**Comment by jieunbyun** [comment]
Do you mean sum( [1 if x in r else 0 for r in c_rules] ) in line 157?
If so, x comes from Line 155 "for x in comps_i:".

**Comment by dynaryu** [comment]
I assumed so, but for loop of comps_i is finished, so the last value of comps_i given the last value of i would be used in that case. You might check the indent if that's not the case. Please let me know.

**Comment by jieunbyun** [comment]
ah I think you mentioned Line 166. It should have been "k". Now it has been fixed. Thank you for noticing this!
